### ISSUE TITLE
Readme: Example for using boinc2docker with input files

### ISSUE THREAD

**Issue by gateware2** [marius311/boinc2docker#10]
So, I basically wrote a little python script which uses another file (which contains input values) to calculate if a value is a prime. As it is written in the Readme, I tried to call the method directly with the input file as the third parameter, but failed:

```
boinc2docker_create_work("python:3-slim", "prim.py", [("input.gz", "input.txt", ['gzip','nodelete'])])
```
```
Automatically setting memory allocation for job to 1072MB.
Automatically setting disk allocation for job to 243MB.
Image already imported into BOINC. Reading existing info...
Creating input template for job...
2019/01/30 00:01:06 [CRITICAL] Error calling ['bin/create_work', '--appname', 'boinc2docker', '--wu_template', '/tmp/tmpnKQCSf/boinc2docker_in_eb799a82049341919b75971e93ad2136', '--rsc_disk_bound', '243200000', '--rsc_memory_bound', '1072800000', 'input_86ac23d84ff4467fb796ecbff6064975.gz', 'vbox_job_64ef8fc5c5e1441296f676581739eecc.xml', 'boinc_app_15e31f84c1f843099b849705f392e399', 'layer_1488fbbf57d360e79f6d873424f9b13988a089e5ba5e2ab76890b64ea0aa3c8a.tar.manual.gz', 'layer_4230c19ce5e2ed765f4bc5d220aafead72404ec5133956cbc068041daf3d121e.tar.manual.gz', 'layer_24303244027e205ffc78e1337511457b0f9e2be91ac56c57bf52eaecefbe46d6.tar.manual.gz', 'layer_7e78452668361394320a34ed59cbc6a2ffc7208b83b9b42f2efaa1f78a7e2abe.tar.manual.gz', 'layer_5894a785dcdb36a0636f6836586e61140aba422877af0063fa30099a6dcc1619.tar.manual.gz', 'image_0769b568426a4c0ec5212e76e4db91852228896ca68fff2673c56b3e99c513b1.tar.manual.gz']:
process_input_template: missing gzip file /home/boincadm/project/download/2b7/input_86ac23d84ff4467fb796ecbff6064975.gz.gz
process_input_template(): file missing
create_work: file missing

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bin/boinc2docker_create_work.py", line 227, in boinc2docker_create_work
    return create_work(appname, create_work_args, [f for _,f,_ in input_files]).strip()
  File "/home/boincadm/project/py/Boinc/create_work.py", line 64, in create_work
    cwd=projdir)
  File "/home/boincadm/project/py/Boinc/create_work.py", line 38, in check_output
    raise CheckOutputError
Boinc.create_work.CheckOutputError
```

Did I miss something? Both files (and the gzip) are just lying in my projects folder on my boinc-server-docker. Maybe a little example in the readme would be helpful for newbies like me.

**Comment by marius311** [comment]
Yes, sorry, this is still pretty poorly documented. You're right an example would be useful. 

In your case I think two problems. The error I *think* is caused because you don't need the `gz` on the first element of that tuple, you should pass the final path you want for the file, and BOINC takes care of unzipping into that filename for you. That second thing though is that the second element in the tuple should be the actual contents of the file, so `open("input.txt").read()` rather than just `"input.txt"`.

**Comment by gateware2** [comment]
Hi, so I tried the following as you suggested:

```
boinc2docker_create_work("python:3-slim", "prim.py", [("input", "open('input.txt').read()", ['gzip','nodelete'])])
```

But still getting the same error:

```
Automatically setting memory allocation for job to 1072MB.
Automatically setting disk allocation for job to 243MB.
Image already imported into BOINC. Reading existing info...
Creating input template for job...
2019/01/30 00:34:58 [CRITICAL] Error calling ['bin/create_work', '--appname', 'boinc2docker', '--wu_template', '/tmp/tmpAaPxbT/boinc2docker_in_8f1ad46687d444a186149b6931261f18', '--rsc_disk_bound', '243200000', '--rsc_memory_bound', '1072800000', 'input_1a378db34f6340a5b5f44bab5751d15d', 'vbox_job_55bc2c32f61749d685de7420d6a19543.xml', 'boinc_app_01c0dfbe2b2e43b3b19e9800c8bef791', 'layer_1488fbbf57d360e79f6d873424f9b13988a089e5ba5e2ab76890b64ea0aa3c8a.tar.manual.gz', 'layer_4230c19ce5e2ed765f4bc5d220aafead72404ec5133956cbc068041daf3d121e.tar.manual.gz', 'layer_24303244027e205ffc78e1337511457b0f9e2be91ac56c57bf52eaecefbe46d6.tar.manual.gz', 'layer_7e78452668361394320a34ed59cbc6a2ffc7208b83b9b42f2efaa1f78a7e2abe.tar.manual.gz', 'layer_5894a785dcdb36a0636f6836586e61140aba422877af0063fa30099a6dcc1619.tar.manual.gz', 'image_0769b568426a4c0ec5212e76e4db91852228896ca68fff2673c56b3e99c513b1.tar.manual.gz']:
process_input_template: missing gzip file /home/boincadm/project/download/18c/input_1a378db34f6340a5b5f44bab5751d15d.gz
process_input_template(): file missing
create_work: file missing

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bin/boinc2docker_create_work.py", line 227, in boinc2docker_create_work
    return create_work(appname, create_work_args, [f for _,f,_ in input_files]).strip()
  File "/home/boincadm/project/py/Boinc/create_work.py", line 64, in create_work
    cwd=projdir)
  File "/home/boincadm/project/py/Boinc/create_work.py", line 38, in check_output
    raise CheckOutputError
Boinc.create_work.CheckOutputError
```

I also thought that the call of the script file itself may be a problem. But if I call this method without the tuple, it works fine (except that the script itself throws errors due to the missing input file). So I think the problem here must be lying in the tuple. I am very sorry to bother you with this little problem. Just hanging around with this awhile and couldn´t figure it out. Also I think this might help other beginners like me :)

**Comment by marius311** [comment]
Ok I can reproduce this and I think I know what the problem is. Until I get around to committing a fix though, try:

```
boinc2docker_create_work("python:3-slim", "prim.py", [("shared/input.txt", open('input.txt').read(), ['nodelete'])])
```

Note you'll need the `shared/` part for the file to end up at `shared/input.txt` inside the container, and no quotes around the `open`.

**Comment by gateware2** [comment]
Ok now it creates the job. :)
I still get a "Calculation Error" in my boinc client when it tries to finish the job, but I think that´s another issue.
Thank you very much for your help with this problem.
I don´t know if I should leave this issue open or close it, so I let you decide :)

**Comment by marius311** [comment]
No problem, we can leave it open until I fix the original issue. Feel free to ask for help with the other problem either here or in a separate issue if you need.

**Comment by gateware2** [comment]
Hi again,
I don´t know if it has something to do with boinc2docker or if it belongs here. But I think it´s worth a try :)
So as mentioned above, I get a "Computation Error" in my boinc client (see screenshot). I also checked the event log of my client and the server logs, but couldn´t find anything useful. At first, I checked if my script may has some errors, but on my local machine it works just fine (it takes a awhile because there are many values in the input.txt but also tried with a much smaller input.txt). I also checked if there are any permission issues on my boinc server, but boincadm has all permissions for the needed files.

That´s the command I used:
```
boinc2docker_create_work("python:3-slim", "prim.py", [("shared/input.txt", open('shared/input.txt').read(), ['nodelete'])])
```
These are the files (screenshot, event log, script and input file):

[boinc2docker_computation_error_files.zip](https://github.com/marius311/boinc2docker/files/2813687/boinc2docker_computation_error_files.zip)

As you can see, the job has been created, but can´t be finished by the client properly. Did I do something wrong? Does the python script miss something (it´s just a quick and dirty prime number identifier)? Im very sorry to bother you with this problem, but couldn´t find any answer elsewhere.
